# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbip_dsp48_macro_0_0/design_1_xbip_dsp48_macro_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_0 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_0} -quiet] -quiet

# Block Designs: bd/bram/bram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram || ORIG_REF_NAME==bram} -quiet] -quiet

# IP: bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_blk_mem_gen_0_0 || ORIG_REF_NAME==bram_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc

# XDC: bd/bram/bram_ooc.xdc
