# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/rpolley/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-11296-CS-S110/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -ruleid {1}  -id {IP_Flow 19-4963}  -string {{WARNING: [IP_Flow 19-4963] design_1_xbip_dsp48_macro_0_0 has board value specified. The packaged IP will be restricted to usage with board 'digilentinc.com:zybo-z7-10:part0:1.0'}}  -suppress 
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/FPGA-Neural-Network-/ip_repo/edit_axis_fifo_v1_0.cache/wt [current_project]
set_property parent.project_path H:/FPGA-Neural-Network-/ip_repo/edit_axis_fifo_v1_0.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_repo_paths {
  h:/FPGA-Neural-Network-/ip_repo/myip_1.0
  h:/FPGA-Neural-Network-/ip_repo/axis_fifo_1.0
  h:/FPGA-Neural-Network-/ip_repo/axis_fifo_1.0
  h:/FPGA-Neural-Network-/ip_repo/axis_fifo_1.0
} [current_project]
set_property ip_output_repo h:/FPGA-Neural-Network-/ip_repo/edit_axis_fifo_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/Buffer.sv
  H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/ConvEngine.sv
  H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/ConvWrapper.sv
  H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/DDR_Shiftreg.sv
  H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/ShiftReg.sv
}
read_verilog -library xil_defaultlib {
  H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/hdl/bram_wrapper.v
  H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  H:/FPGA-Neural-Network-/ip_repo/axis_fifo_1.0/hdl/axis_fifo_v1_0.v
}
add_files H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

add_files H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/bram.bd
set_property used_in_implementation false [get_files -all h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/bram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top axis_fifo_v1_0 -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef axis_fifo_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file axis_fifo_v1_0_utilization_synth.rpt -pb axis_fifo_v1_0_utilization_synth.pb"
