set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:1 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[0].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:2 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[1].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:3 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[2].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:4 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[3].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:5 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[4].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:6 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[5].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:7 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[6].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:8 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[7].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:9 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[8].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:10 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[9].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:11 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[10].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:12 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[11].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:13 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[12].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:14 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[13].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:15 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[14].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:16 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[15].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:17 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[16].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:18 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[17].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:19 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[18].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:20 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[19].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:21 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[20].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:22 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[21].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:23 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[22].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:24 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[23].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:25 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[0].channel[24].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:26 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[0].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:27 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[1].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:28 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[2].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:29 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[3].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:30 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[4].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:31 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[5].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:32 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[6].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:33 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[7].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:34 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[8].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:35 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[9].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:36 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[10].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:37 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[11].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:38 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[12].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:39 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[13].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:40 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[14].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:41 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[15].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:42 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[16].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:43 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[17].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:44 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[18].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:45 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[19].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:46 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[20].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:47 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[21].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:48 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[22].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:49 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[23].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:50 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[1].channel[24].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:51 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[0].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:52 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[1].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:53 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[2].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:54 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[3].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:55 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[4].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:56 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[5].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:57 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[6].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:58 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[7].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:59 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[8].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:60 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[9].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:61 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[10].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:62 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[11].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:63 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[12].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:64 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[13].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:65 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[14].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:66 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[15].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:67 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[16].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:68 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[17].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:69 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[18].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:70 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[19].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:71 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[20].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:72 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[21].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:73 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[22].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:74 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[23].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1_board.xdc id:75 order:EARLY used_in_board:yes scoped_inst:{engine/buffers[2].channel[24].conv/mult_acc/design_1_i/clk_wiz/inst} prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:76 order:EARLY scoped_inst:{engine/buffers[0].channel[0].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:77 order:EARLY scoped_inst:{engine/buffers[0].channel[1].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:78 order:EARLY scoped_inst:{engine/buffers[0].channel[2].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:79 order:EARLY scoped_inst:{engine/buffers[0].channel[3].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:80 order:EARLY scoped_inst:{engine/buffers[0].channel[4].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:81 order:EARLY scoped_inst:{engine/buffers[0].channel[5].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:82 order:EARLY scoped_inst:{engine/buffers[0].channel[6].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:83 order:EARLY scoped_inst:{engine/buffers[0].channel[7].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:84 order:EARLY scoped_inst:{engine/buffers[0].channel[8].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:85 order:EARLY scoped_inst:{engine/buffers[0].channel[9].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:86 order:EARLY scoped_inst:{engine/buffers[0].channel[10].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:87 order:EARLY scoped_inst:{engine/buffers[0].channel[11].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:88 order:EARLY scoped_inst:{engine/buffers[0].channel[12].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:89 order:EARLY scoped_inst:{engine/buffers[0].channel[13].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:90 order:EARLY scoped_inst:{engine/buffers[0].channel[14].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:91 order:EARLY scoped_inst:{engine/buffers[0].channel[15].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:92 order:EARLY scoped_inst:{engine/buffers[0].channel[16].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:93 order:EARLY scoped_inst:{engine/buffers[0].channel[17].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:94 order:EARLY scoped_inst:{engine/buffers[0].channel[18].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:95 order:EARLY scoped_inst:{engine/buffers[0].channel[19].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:96 order:EARLY scoped_inst:{engine/buffers[0].channel[20].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:97 order:EARLY scoped_inst:{engine/buffers[0].channel[21].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:98 order:EARLY scoped_inst:{engine/buffers[0].channel[22].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:99 order:EARLY scoped_inst:{engine/buffers[0].channel[23].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:100 order:EARLY scoped_inst:{engine/buffers[0].channel[24].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:101 order:EARLY scoped_inst:{engine/buffers[1].channel[0].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:102 order:EARLY scoped_inst:{engine/buffers[1].channel[1].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:103 order:EARLY scoped_inst:{engine/buffers[1].channel[2].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:104 order:EARLY scoped_inst:{engine/buffers[1].channel[3].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:105 order:EARLY scoped_inst:{engine/buffers[1].channel[4].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:106 order:EARLY scoped_inst:{engine/buffers[1].channel[5].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:107 order:EARLY scoped_inst:{engine/buffers[1].channel[6].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:108 order:EARLY scoped_inst:{engine/buffers[1].channel[7].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:109 order:EARLY scoped_inst:{engine/buffers[1].channel[8].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:110 order:EARLY scoped_inst:{engine/buffers[1].channel[9].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:111 order:EARLY scoped_inst:{engine/buffers[1].channel[10].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:112 order:EARLY scoped_inst:{engine/buffers[1].channel[11].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:113 order:EARLY scoped_inst:{engine/buffers[1].channel[12].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:114 order:EARLY scoped_inst:{engine/buffers[1].channel[13].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:115 order:EARLY scoped_inst:{engine/buffers[1].channel[14].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:116 order:EARLY scoped_inst:{engine/buffers[1].channel[15].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:117 order:EARLY scoped_inst:{engine/buffers[1].channel[16].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:118 order:EARLY scoped_inst:{engine/buffers[1].channel[17].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:119 order:EARLY scoped_inst:{engine/buffers[1].channel[18].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:120 order:EARLY scoped_inst:{engine/buffers[1].channel[19].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:121 order:EARLY scoped_inst:{engine/buffers[1].channel[20].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:122 order:EARLY scoped_inst:{engine/buffers[1].channel[21].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:123 order:EARLY scoped_inst:{engine/buffers[1].channel[22].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:124 order:EARLY scoped_inst:{engine/buffers[1].channel[23].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:125 order:EARLY scoped_inst:{engine/buffers[1].channel[24].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:126 order:EARLY scoped_inst:{engine/buffers[2].channel[0].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:127 order:EARLY scoped_inst:{engine/buffers[2].channel[1].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:128 order:EARLY scoped_inst:{engine/buffers[2].channel[2].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:129 order:EARLY scoped_inst:{engine/buffers[2].channel[3].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:130 order:EARLY scoped_inst:{engine/buffers[2].channel[4].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:131 order:EARLY scoped_inst:{engine/buffers[2].channel[5].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:132 order:EARLY scoped_inst:{engine/buffers[2].channel[6].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:133 order:EARLY scoped_inst:{engine/buffers[2].channel[7].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:134 order:EARLY scoped_inst:{engine/buffers[2].channel[8].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:135 order:EARLY scoped_inst:{engine/buffers[2].channel[9].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:136 order:EARLY scoped_inst:{engine/buffers[2].channel[10].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:137 order:EARLY scoped_inst:{engine/buffers[2].channel[11].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:138 order:EARLY scoped_inst:{engine/buffers[2].channel[12].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:139 order:EARLY scoped_inst:{engine/buffers[2].channel[13].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:140 order:EARLY scoped_inst:{engine/buffers[2].channel[14].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:141 order:EARLY scoped_inst:{engine/buffers[2].channel[15].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:142 order:EARLY scoped_inst:{engine/buffers[2].channel[16].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:143 order:EARLY scoped_inst:{engine/buffers[2].channel[17].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:144 order:EARLY scoped_inst:{engine/buffers[2].channel[18].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:145 order:EARLY scoped_inst:{engine/buffers[2].channel[19].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:146 order:EARLY scoped_inst:{engine/buffers[2].channel[20].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:147 order:EARLY scoped_inst:{engine/buffers[2].channel[21].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:148 order:EARLY scoped_inst:{engine/buffers[2].channel[22].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:149 order:EARLY scoped_inst:{engine/buffers[2].channel[23].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property SRC_FILE_INFO {cfile:h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc rfile:../fpga.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xdc id:150 order:EARLY scoped_inst:{engine/buffers[2].channel[24].conv/mult_acc/design_1_i/clk_wiz/inst}} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:11 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:12 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:13 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:14 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:15 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:16 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:17 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:18 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:19 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:20 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:21 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:22 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:23 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:24 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:25 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:26 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:27 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:28 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:29 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:30 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:31 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:32 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:33 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:34 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:35 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:36 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:37 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:38 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:39 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:40 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:41 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:42 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:43 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:44 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:45 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:46 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:47 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:48 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:49 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:50 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:51 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:52 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:53 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:54 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:55 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:56 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:57 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:58 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:59 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:60 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:61 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:62 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:63 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:64 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:65 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:66 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:67 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:68 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:69 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:70 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:71 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:72 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:73 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:74 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:75 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {sys_clk} [get_ports clk_in1]
set_property src_info {type:SCOPED_XDC file:76 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:77 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:78 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:79 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:80 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:81 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:82 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:83 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:84 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:85 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:86 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:87 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:88 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:89 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:90 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:91 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:92 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:93 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:94 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:95 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:96 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:97 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:98 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:99 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:100 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:101 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:102 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:103 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:104 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:105 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:106 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:107 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:108 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:109 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:110 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:111 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:112 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:113 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:114 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:115 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:116 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:117 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:118 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:119 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:120 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:121 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:122 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:123 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:124 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:125 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:126 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:127 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:128 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:129 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:130 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:131 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:132 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:133 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:134 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:135 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:136 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:137 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:138 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:139 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:140 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:141 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:142 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:143 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:144 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:145 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:146 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:147 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:148 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:149 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:SCOPED_XDC file:150 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
