# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "H:/FPGA-Neural-Network-/fpga/.Xil/Vivado-32736-CS-S110/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ipshared/5123 {
      H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/Buffer.sv
      H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/ConvEngine.sv
      H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/ConvWrapper.sv
      H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/DDR_Shiftreg.sv
      H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/new/ShiftReg.sv
      C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/ipshared/5123 {
      H:/FPGA-Neural-Network-/fpga/.Xil/Vivado-32736-CS-S110/realtime/design_1_xbip_dsp48_macro_0_0_stub.v
      H:/FPGA-Neural-Network-/fpga/.Xil/Vivado-32736-CS-S110/realtime/design_1_clk_wiz_1_stub.v
      H:/FPGA-Neural-Network-/fpga/.Xil/Vivado-32736-CS-S110/realtime/bram_blk_mem_gen_0_0_stub.v
      H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/synth/design_1.v
      H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/synth/bram.v
      H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/hdl/bram_wrapper.v
      H:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
      h:/FPGA-Neural-Network-/ip_repo/axis_fifo_1.0/hdl/axis_fifo_v1_0.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top axis_fifo_v1_0
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "H:/FPGA-Neural-Network-/fpga/.Xil/Vivado-32736-CS-S110/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
