# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_1/bram_blk_mem_gen_0_1.xci
# IP: The module: 'bram_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_1/bram_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_1/bram_blk_mem_gen_0_1.xci
# IP: The module: 'bram_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/FPGA-Neural-Network-/fpga/fpga.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_1/bram_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
