# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/ip/System_axis_fifo_0_0/System_axis_fifo_0_0.xci
# IP: The module: 'System_axis_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_xbip_dsp48_macro_0_0/design_1_xbip_dsp48_macro_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_0 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_0} -quiet] -quiet

# IP: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_blk_mem_gen_0_0 || ORIG_REF_NAME==bram_blk_mem_gen_0_0} -quiet] -quiet

# XDC: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0_ooc.xdc

# XDC: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/bram/bram_ooc.xdc

# XDC: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/design_1/design_1_ooc.xdc

# IP: H:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/ip/System_axis_fifo_0_0/System_axis_fifo_0_0.xci
# IP: The module: 'System_axis_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/design_1/ip/design_1_xbip_dsp48_macro_0_0/design_1_xbip_dsp48_macro_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbip_dsp48_macro_0_0 || ORIG_REF_NAME==design_1_xbip_dsp48_macro_0_0} -quiet] -quiet

# IP: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_blk_mem_gen_0_0 || ORIG_REF_NAME==bram_blk_mem_gen_0_0} -quiet] -quiet

# XDC: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0_ooc.xdc

# XDC: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/bram/bram_ooc.xdc

# XDC: h:/FPGA-Neural-Network-/System/System.srcs/sources_1/bd/System/fpga/fpga.srcs/sources_1/bd/design_1/design_1_ooc.xdc
